name: Update latexdiff on change
on:
  push:
    # Add file paths here to trigger the workflow only when these files are modified (optional)
    paths:
    - main.tex
jobs:
  latexdiff-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install latexdiff
        run: sudo apt install latexdiff
      - name: Install git-latexdiff
        run: |
          git clone 'https://gitlab.com/git-latexdiff/git-latexdiff.git'
          cd git-latexdiff
          sudo make install-bin
          cd ../
          git latexdiff HEAD^^ -o 'diff.pdf'
      - uses: actions/upload-artifact@v2
        with:
          name: diff
          path: diff.pdf